# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d69c2c6c9b7aae648ab11c61df9beaaccf5be91df0963e4c4085dd50ebf8edcf1b073f38635681eff0cf718bd09e8028b684484e584fe19fa40856bddd5134bd

test:
  secret_key_base: c9c4caf1975309346817b300d87338bd6f049a63ffeb330a81b0a801d562373bcb33ef6163fe143f5f105c18e64128d366ee5f8a124bb3ca74c1a72a63e3f7e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
